# Generated by Django 4.1 on 2024-01-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=200)),
                ('ctc', models.IntegerField()),
                ('adress', models.CharField(max_length=300)),
                ('education', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emai', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
    ]
