# Generated by Django 4.1 on 2024-01-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='photo',
            field=models.ImageField(default='', upload_to='images/images'),
        ),
    ]
