# Generated by Django 4.1 on 2024-01-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0003_alter_userdetails_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
