# Generated by Django 4.1 on 2024-01-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0004_alter_userdetails_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='photo',
            field=models.BinaryField(),
        ),
    ]
