# Generated by Django 4.1 on 2024-02-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0005_alter_userdetails_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.EmailField(max_length=254)),
                ('date', models.CharField(max_length=254)),
                ('task', models.TextField()),
            ],
        ),
    ]
