# Generated by Django 4.1 on 2024-02-22 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0006_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='role',
            field=models.CharField(default='user', max_length=20),
            preserve_default=False,
        ),
    ]
