# Generated by Django 4.1 on 2024-02-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0007_userdetails_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='role',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
