# Generated by Django 4.1 on 2024-02-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0011_remove_userdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='role',
            field=models.CharField(default='user', max_length=20),
            preserve_default=False,
        ),
    ]
