# Generated by Django 4.1 on 2024-03-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0012_userdetails_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminemail', models.EmailField(max_length=254)),
                ('date', models.CharField(max_length=254)),
                ('news', models.TextField()),
            ],
        ),
    ]
